// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOp147K69Ci6cQNGA2MTCQk_vF-nlT9C4',
    appId: '1:462293184464:web:fac53e40d506d40f3f13d5',
    messagingSenderId: '462293184464',
    projectId: 'newsfeed-ecs198f',
    authDomain: 'newsfeed-ecs198f.firebaseapp.com',
    storageBucket: 'newsfeed-ecs198f.appspot.com',
    measurementId: 'G-33MGP8J0SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj7a8xTSmvzQPDwZodkHhG2e40Vdqx3AE',
    appId: '1:462293184464:android:e930e1c46df046003f13d5',
    messagingSenderId: '462293184464',
    projectId: 'newsfeed-ecs198f',
    storageBucket: 'newsfeed-ecs198f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGvF6Fz0qWXaHWzr5hF7cMP3OyDWdeiAk',
    appId: '1:462293184464:ios:269fe402d3489d353f13d5',
    messagingSenderId: '462293184464',
    projectId: 'newsfeed-ecs198f',
    storageBucket: 'newsfeed-ecs198f.appspot.com',
    iosClientId: '462293184464-ammmp4uf3384t84mjt1v9ieamh3avffb.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsFeed',
  );
}
